### PR TITLE
Fix seek issue with CoreELEC devices

### PR DESCRIPTION
**Pull request by bowlingbeeg**
GHI (If applicable): #

## Description: 
Change the seek fix for the Ugoos am6b+ generic for all CoreELEC users.

## Checklist:
- [X] I have based this PR against the develop branch

### CODE REVIEW

**Comment by pannal** [comment]
Thank you! Can you use platform.uname in a way that's compatible with python 2? (since 3.3 platform.uname returns a named tuple, before it returned a tuple)

So instead of accessing the named tuple, unpack it to make it compatible with py2.

If you're not sure what I mean, I can merge this and fix it on my end.

**Comment by bowlingbeeg** [comment]
When I looked at the documentation to make sure I wasn't missing anything I realized that what I was checking was actually the network name which didn't seem correct.  So I changed to use the lsb_release command and look for CoreELEC.

**Comment by bowlingbeeg** [comment]
Wonder if I should add a check for "linux" ... maybe the platform.system() call would give me what I want.  Or I guess I could check for either system.platform.linux or system.platform.linux.raspberrypi

**Comment by pannal** [comment]
Yeah we already have that, in lib/util.py:971, it contains "Linux" or "RaspberryPi".

Oh you've already spotted that :)

**Pull request merged**
