### PR TITLE
updated strings.po Spanish.

### PR DESCRIPTION
**Pull request by Deci8BelioS**
GHI (If applicable): #

## Checklist:
- [x] I have based this PR against the develop branch

### CODE REVIEW

**Comment by pannal** [comment]
Thank you, I'll only merge the updated strings. I'll adjust addon.xml for the release versions to `reuselanguageinvoker` and I won't merge the changed icon.

Please drop the other commits apart from the PO changes.

**Comment by Deci8BelioS** [comment]
> Thank you, I'll only merge the updated strings. I'll adjust addon.xml for the release versions to `reuselanguageinvoker` and I won't merge the changed icon.
> 
> Please drop the other commits apart from the PO changes.

I have already reverted the addon icon, should I leave the addon.xml file as the original one?

**Comment by pannal** [comment]
Yes, please. I'm adding `reuselanguageinvoker` by default and have developed a setting to toggle this feature.

**Comment by Deci8BelioS** [comment]
> Yes, please. I'm adding `reuselanguageinvoker` by default and have developed a setting to toggle this feature.

I just changed the file

**Comment by pannal** [comment]
Hmm. Why would you think `reuselanguageinvoker` would make any difference for this addon? It's long running, so the invoker would not have to be reused anyways, as long as one doesn't re-open the addon multiple times.

**Comment by Deci8BelioS** [comment]
> Hmm. Why would you think `reuselanguageinvoker` would make any difference for this addon? It's long running, so the invoker would not have to be reused anyways, as long as one doesn't re-open the addon multiple times.

I honestly don't know exactly what it does, I thought it was to get the language you have set in kodi.

**Comment by pannal** [comment]
No, that's about the Python language invoker, not languages. Those work just by existing AFAIK.

**Pull request merged**
