### PR TITLE
Fix issue on CoreELEC where selecting new audio stream causes video to start over.

### PR DESCRIPTION
**Pull request by bowlingbeeg**
GHI (If applicable): #
N/A

## Description:
There is a timing issue after the video is restarted with the new audio stream. The seek back to the spot where the audio stream was changed is being ignored by Kodi. Adding in a delay before issuing the seek fixes the issue.

## Checklist:
- [X] I have based this PR against the develop branch

### CODE REVIEW

**Comment by pannal** [comment]
Hmm, not sure if this is the right solution - is the player failing for you as well? https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2548

**Comment by pannal** [comment]
I mean in their case it closes with a FAILED state, not "just" restarting; does it do the same for you or does it simply restart properly?

**Comment by pannal** [comment]
Wait, I think the cause of this issue is related to embedded subtitles.

**Comment by pannal** [comment]
This might be implicitly fixed with: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2559, please confirm

**Comment by bowlingbeeg** [comment]
Yeah, in my case it wasn't crashing, just not doing the seek after restarting the video.  I did happen to be using a movie with a subtitle so maybe that was the cause.  I'll try it out tonight and see if it happens with just that change and/or if I can reproduce the problem with a movie that doesn't have a subtitle.

**Comment by bowlingbeeg** [comment]
ok, so I ran some tests tonight and here is what I found.

1. This issues started in 7.9 beta 6.1 which is the same one that I made the change in for the seek issue.  I went back to beta 5.2 and couldn't reproduce.  So it's definitely related to that other seek command we're using on CoreELEC.
2. I can reproduce this on videos with and without subtitles.  I also tested with your subtitle "fix" to hold off on doing the seek just in case and was still able to reproduce.
3. I was also able to reproduce the issue on the latest 16.4 beta.  If the switching of streams doesn't cause us to restart the video then it doesn't reproduce the issue(obviously) but when forcing the audio stream to transcode then the issue reproduces.
4. The new switching of audio streams re-introduces the issue we had with the seek where the audio won't start back up for a few seconds.  Not sure what to do about that one.  Maybe there is another "switch streams" call that works better in CoreELEC.

So I this PR is still needed.  Maybe you have an idea for a better way of doing it instead of just hard coding some delay.  But without this PR then CoreELEC users could still run into the issue of the video stream starting from the beginning when switching streams.

**Comment by pannal** [comment]
Thanks for testing! 

Having a fixed delay is always a bad idea, as we're obviously dealing with a timing issue, here, and we can't guarantee, that the 500ms is necessary for certain clients, or not enough for others.

I'll merge this, if this fixes the issue, but _please_ try and ping the CE guys about the seek issue. This (the original issue with the seek functionality) isn't something we should work around.

**Comment by pannal** [comment]
Can you get me a log about this issue using my latest beta? We might be able to verify that seekOnStart happened, and re-seek until it did. That might be a better fix.

**Comment by bowlingbeeg** [comment]
Yeah I agree, I don't like the hardcoded delay but I'm not sure what else we could do.  I don't really know where to start with CoreELEC team.

**Comment by bowlingbeeg** [comment]
I'm going to be out of town for a couple of days so I won't be able to provide you a debug log until next week.

**Comment by pannal** [comment]
OK, no worries! I _think_ we can check whether we've actually done the seekOnStart, but for that I need a debug log to see the order of events and where to fix this.

**Comment by pannal** [comment]
> The new switching of audio streams re-introduces the issue we had with the seek where the audio won't start back up for a few seconds. Not sure what to do about that one. Maybe there is another "switch streams" call that works better in CoreELEC.

Maybe we can issue an immediate seek-back of -100ms in this case for CoreELEC.

**Comment by pannal** [comment]
Looking at the log from a CE user:
```
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: Notification: xbmc Player.OnAVChange {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"speed":1}}
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: Notification: xbmc Player.OnAVStart {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"speed":1}}
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: Player - AVChange
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: SeekHandler: onAVChange
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: SeekDialog: OnAVChange: DPO: 0, offset: 0
2024-07-29 15:22:49.092 T:1235     info <general>: script.plex: Player - SEEK: 4158000
2024-07-29 15:22:49.093 T:1235     info <general>: script.plex: SeekHandler: onPlayBackSeek - 4158427, 4158000, 4159000
2024-07-29 15:22:49.093 T:1235     info <general>: script.plex: SeekDialog: OnPlaybackSeek: 4158427, 4158000
2024-07-29 15:22:49.094 T:1874     info <general>: script.plex: API: DEBUG: Timer <bound method SeekDialog.onTimeKeeperCallback of <lib.windows.seekdialog.SeekDialog object at 0x7f75b4de20>>: STARTED
2024-07-29 15:22:49.126 T:1235     info <general>: script.plex: SeekHandler: offset=None, settings_changed=False, seeking=2, state=playing
2024-07-29 15:22:49.127 T:1235     info <general>: script.plex: OnPlayBackSeek: Seeked on start to: 4158427
2024-07-29 15:22:49.127 T:1235     info <general>: script.plex: Notification: xbmc Player.OnAVChange {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"speed":1}}
2024-07-29 15:22:49.127 T:1235     info <general>: script.plex: Notification: xbmc Player.OnSeek {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"seekoffset":{"hours":1,"milliseconds":0,"minutes":9,"seconds":18},"speed":1,"time":{"hours":1,"milliseconds":427,"minutes":9,"seconds":18}}}
2024-07-29 15:22:49.127 T:1235     info <general>: script.plex: Player - AVChange
2024-07-29 15:22:49.127 T:1235     info <general>: script.plex: SeekHandler: onAVChange
2024-07-29 15:22:49.128 T:1235     info <general>: script.plex: SeekDialog: OnAVChange: DPO: 0, offset: 4158427
2024-07-29 15:22:49.128 T:1235     info <general>: script.plex: Notification: xbmc Player.OnAVChange {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"speed":1}}
2024-07-29 15:22:49.166 T:1238     info <general>: script.plex: Player: Seek OSD opened
2024-07-29 15:22:49.167 T:1873     info <general>: CAEStreamParser::TrySyncAC3 - E-AC3 stream detected (6 channels, 48000Hz)
2024-07-29 15:22:49.167 T:1873     info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, pass-through)
2024-07-29 15:22:49.253 T:1050     info <general>: CAESinkALSA::Initialize - Configure simple control for "AUGESOUND"
2024-07-29 15:22:49.254 T:1050     info <general>: CAESinkALSA - Use card "hw:0" and set codec format "2 CH PCM"
2024-07-29 15:22:49.255 T:1050     info <general>: CAESinkALSA - Set Spdif to HDMITX to "Spdif_b"
2024-07-29 15:22:49.255 T:1050     info <general>: CAESinkALSA - Set codec for "Audio spdif_b format"
2024-07-29 15:22:49.255 T:1050     info <general>: CAESinkALSA - Set codec for "Audio I2S to HDMITX Format"
2024-07-29 15:22:49.255 T:1050     info <general>: CAESinkALSA - Set codec for "Audio spdif format"
2024-07-29 15:22:49.255 T:1050     info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=AMLAUGESOUND,DEV=0"
2024-07-29 15:22:49.264 T:1050     info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=AMLAUGESOUND,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2024-07-29 15:22:49.264 T:1050     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-07-29 15:22:49.264 T:1050     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S16NE
2024-07-29 15:22:49.282 T:1050     info <general>: CActiveAESink::OpenSink - initialize sink
2024-07-29 15:22:49.283 T:1050     info <general>: CAESinkALSA::Initialize - Configure simple control for "AUGESOUND"
2024-07-29 15:22:49.283 T:1050     info <general>: CAESinkALSA - Use card "hw:0" and set codec format "DD+"
2024-07-29 15:22:49.285 T:1050     info <general>: CAESinkALSA - Set Spdif to HDMITX to "Spdif_b"
2024-07-29 15:22:49.285 T:1050     info <general>: CAESinkALSA - Set codec for "Audio spdif_b format"
2024-07-29 15:22:49.285 T:1050     info <general>: CAESinkALSA - Set codec for "Audio I2S to HDMITX Format"
2024-07-29 15:22:49.285 T:1050     info <general>: CAESinkALSA - Set codec for "Audio spdif format"
2024-07-29 15:22:49.288 T:1050     info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=AMLAUGESOUND,DEV=0"
2024-07-29 15:22:49.307 T:1050     info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=AMLAUGESOUND,DEV=0,AES0=0x06,AES1=0x82,AES2=0x00,AES3=0x0e"
2024-07-29 15:22:49.428 T:1235     info <general>: script.plex: Player - AVChange
2024-07-29 15:22:49.429 T:1235     info <general>: script.plex: SeekHandler: onAVChange
2024-07-29 15:22:49.429 T:1235     info <general>: script.plex: SeekDialog: OnAVChange: DPO: 0, offset: 4158427
2024-07-29 15:22:49.429 T:1235     info <general>: script.plex: Notification: xbmc Player.OnAVChange {"item":{"title":"Bad Boys: Até o Fim","type":"movie","year":2024},"player":{"playerid":-1,"speed":1}}
2024-07-29 15:22:50.290 T:1238     info <general>: script.plex: UpdateNowPlaying: 8681, force: True refreshQueue: False state: None overrideChecks: False time: None
2024-07-29 15:22:50.295 T:1879     info <general>: script.plex: API: Starting request: GET https://192-168-1-4.c62f760bf6874b0ba9129a4a6f81c2df.plex.direct:32400/:/timeline?time=518&duration=6958201&state=playing&guid=plex%3A//movie/5ea7e56c39b61600418c0b44&ratingKey=8681&key=/library/metadata/8681&containerKey=/hubs/home/continueWatching&X-Plex-Token=**** (async=True timeout=10.0(5.0))
2024-07-29 15:22:51.750 T:1238     info <general>: script.plex: UpdateNowPlaying: 8681, force: True refreshQueue: False state: None overrideChecks: False time: None
2024-07-29 15:22:55.196 T:1235     info <general>: Skipped 2 duplicate messages..
2024-07-29 15:22:55.196 T:1235     info <general>: script.plex: SeekDialog: Closing
2024-07-29 15:22:55.196 T:1874     info <general>: script.plex: API: DEBUG: Timer <bound method SeekDialog.onTimeKeeperCallback of <lib.windows.seekdialog.SeekDialog object at 0x7f75b4de20>>: FINISHED
2024-07-29 15:22:55.274 T:1032     info <general>: CVideoPlayer::CloseFile()
```

You can see at the end of the log that it sends `/:/timeline?time=518`. It seems like the seek to 4158000 actually happened, but then the resume point gets killed for some reason.

**Comment by pannal** [comment]
This might fix that: https://github.com/pannal/plex-for-kodi/commit/d03c57978fff2e1ed57f040d3f3918af626d4de7

**Comment by pannal** [comment]
I'm guessing in this specific instance/with CoreELEC, while switching the stream, the player resets its current time. While that happens, our `tick()` method from `SeekPlayerHandler` runs and stores the bad time in the Plex server. This leads to the loss of the resume state and the apparent "bug".

Your fix might still be necessary, but this way, at least this shouldn't happen anymore (I've confirmed with the user that the resume state was gone when this happened).

Edit: This fix also avoids sending a timeline event while its still waiting for seekOnStart to be applied.

**Comment by pannal** [comment]
> This issues started in 7.9 beta 6.1 which is the same one that I made the change in for the seek issue. I went back to beta 5.2 and couldn't reproduce. So it's definitely related to that other seek command we're using on CoreELEC.

We have a similar issue on official Kodi with embedded subtitle streams that don't start immediately. I've fixed that by applying a -100ms seek-back. Maybe the same thing works for the original issue you've fixed in CE.

**Comment by pannal** [comment]
Just had a long session with a user; this fixes the seekOnStart issues on CE: https://github.com/pannal/plex-for-kodi/commit/792b0fb1a33dc8838515a2168bc049e257286a5c

**Comment by bowlingbeeg** [comment]
You had a busy weekend ... I just got home and tried out your latest beta and I can confirm that I no longer see the issue where the stream restarts from the beginning.  So this PR isn't needed anymore.  What is strange is that I do see more of those same audio issues with this change.  The ones where the audio is silent or stutters for up to 15 seconds.  So now I see it almost every time when switching audio streams that don't require a restart of the video and occasionally when switching streams that do require a restart of the video.

**Comment by pannal** [comment]
Yeah, it seems like audio stream switching is very borked on CE. All this stuff shouldn't be necessary at all. Ignoring seek commands, timing issues, etc, meh.

Also the fix I've linked isn't always stable for the user, I'll check tomorrow.

Edit: in their logs I've regularly seen kodi reporting massive audio offset delays that it fixes after a while, when switching audio streams. That's probably the actual root cause for all this.

**Comment by pannal** [comment]
You can try adding a negative seek to the audio switch code, just as I did for embedded subtitles (-100ms). Maybe that fixes it.

**Comment by bowlingbeeg** [comment]
Yeah, I've seen those large audio offsets as well when things are really bad.  I did try adding in the -100ms to the switch audio path but if I do it right away it doesn't help.  And I don't know of anything that I can check for to know when Kodi will actually honor the seek.  I did add a 500ms delay and then it worked but again that's just hacky.  My last thought was to try and tell from the player time if things actually went back 100ms and if they didn't re-issue the seek but I'm not sure how well that will work.  If I get some time tonight I'll give that a try.

One thing that concerned me looking at your fix is that after the first seek on line 614 there is no waiting before checking the time and entering the loop where you would issue another seek.  Is it possible that's causing some stability issues?

**Comment by pannal** [comment]
Yes it is. Evertonmdz just tested a fix for double seeking (your coreelec specific fix using relativeseek double seeks sometimes with the new CE resume fix) seekOnStart. The simple fix is adding a small sleep before the first immediate seek. I think it's possible to do this in a cleaner way by checking the player's seek state. I'll investigate.

**Comment by pannal** [comment]
This whole thing is a dumpster fire. It should _not_ be necessary. Running Kodi semi blindly as the boot UI without a proper core development team is a bad idea. As it stands, CoreELEC is a good idea badly executed IMHO.

Kodi's meant to always behave the same.

**Comment by pannal** [comment]
> My last thought was to try and tell from the player time if things actually went back 100ms and if they didn't re-issue the seek but I'm not sure how well that will work

Hmm. Might be a good idea to separate my fix into a "make sure we've seeked" function.

**Comment by pannal** [comment]
>  I did add a 500ms delay and then it worked but again that's just hacky.

You might want to react to onAVChange and then seek. Keep the state about switching audio, then do the seek once that's happened via that callback. Might be a better fix for the resume issue as well, but my current fix works well enough, and I'm not looking forward to another two days of testing asynchronously with a user :D

**Comment by bowlingbeeg** [comment]
So I've been trying lots of combinations over the last couple of days to try and work around the stream switching issue where audio stutters or is delayed.  I think I found something that works that also isn't just a hardcoded wait.  I uploaded a new PR for it, https://github.com/pannal/plex-for-kodi/pull/135

**Pull request closed without merging**
