### PR TITLE
Fix button size issue when multiple media versions exist

### PR DESCRIPTION
**Pull request by bowlingbeeg**
- The function that is getting called to resize the buttons is called for every episode in the season so the button sizes keep getting reset as each episode loads.  This fix will only calculate the size for the episode that is selected.  It also will re-calculate the button size every time a new episode is selected.

GHI (If applicable): #

## Checklist:
- [X] I have based this PR against the develop branch

### CODE REVIEW

**Comment by bowlingbeeg** [comment]
ok, uploaded a new version with the hardcoded xml changes for the button sizes.  Let me know if you like this better.

**Comment by pannal** [comment]
Hmm, I'm not sure duplicating IDs is a good idea. I don't know how the Kodi XML engine handles this, but I'd avoid it. Maybe it's time we look into [this](https://kodi.wiki/view/Skinning_Manual#Use_params_in_includes), which should also help us with copy&paste code in general.

Edit: Look at [this](https://kodi.wiki/view/Skinning_Manual#Variables) as well.

**Comment by pannal** [comment]
Do you want me to merge this and test the includes myself or do you want to take a look?

**Comment by pannal** [comment]
Damn, includes don't seem to work with addons.

**Comment by bowlingbeeg** [comment]
Yeah, was going to say that I tried the includes stuff and couldn't get it to work.  I tried searching online for other ways to do it but couldn't really find anything that worked.

**Comment by pannal** [comment]
OK, found a clean solution that doesn't involve duplicate control IDs. It's a little complicated but seems stable, will push later today. Based on this PR.

**Pull request merged**
