### PR TITLE
Updates to reposition and align ratings on the pre-play screen

### PR DESCRIPTION
**Pull request by rdswords**
GHI (If applicable): #69

## Checklist:
- [X] I have based this PR against the develop branch

### CODE REVIEW

**Comment by rdswords** [comment]
@pannal Just a reminder that this request is still open and should still be valid against all recent comments

**Comment by pannal** [comment]
Thanks!

**Comment by pannal** [comment]
Wait. Why doesn't that look right?
image

**Comment by pannal** [comment]
Reverting your change yields:
image

(which is arguably better I think)

**Comment by pannal** [comment]
This is with posy 2 on the group list and posy 2 on both images:
image

**Comment by pannal** [comment]
posy 4 on the grouplist and posy 2 on the images:
image


Which imho is perfect.

**Comment by rdswords** [comment]
Did you get the height change of the group from 32 to 60 that those values should align to?

**Comment by pannal** [comment]
Yeah I've seen that, it's the first screenshot

**Comment by pannal** [comment]
I'll stick with my last configuration for 0.7.1, if you want to change it, we can, but that's not going to make it for 0.7.1 as I'm preparing its release now

**Comment by pannal** [comment]
Sorry, I should've checked on the PR branch before merging this

**Comment by rdswords** [comment]
With the height of the group lists matched at 60 for the title text and the review elements, and the height of each element in the review group matched at 30, the posy of 15 for the elements in the review group should have them placed to align with the vertical center of the 60 height elements. It all aligns on my end unless some value is being missed by one of us.

Screenshot_20231216-162456

**Pull request merged**
